apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi