apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-role
  namespace: demo
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
  # resources: ["pods", "services", "deployments", "configmaps", "secrets"]
  # verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]