- name: "My first play []"
  hosts: master-1  ## all, 
  tasks:
  
  - name: "[pre] apt update"
    apt:
      update_cache: yes
    become: true
    tags: 
      - pre

  - name: k9s 설치
    shell: |   
      curl -sL https://github.com/derailed/k9s/releases/download/v0.25.21/k9s_Linux_x86_64.tar.gz | sudo tar xfz - -C /usr/local/bin k9s
    tags: 
      - k9s 
