
- name: "My step2 play []"
  hosts: all  ## all, 

  tasks:
  - name: "pip 설치"
    apt: 
      name: python3-pip   
    become: true  
    tags: 
    - pip
    - pre    
  - name: install ansible server module pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 
    tags: 
      - ansible-module
      - pre

  - name: helm3 설치
    shell: |
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash    
    tags: 
      - helm
      
  - name: "bitnami  repository 추가" 
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami
    tags: 
      - bitnami-repo
      - helm
    

  ############### helm repo update #################### 
  - name: helm repo update
    shell: |
      helm repo update
    tags: 
      - helm-update
      - helm

  - name: redis 설치
    kubernetes.core.helm:
      name: redis
      chart_ref: bitnami/redis
      chart_version: "{{REDIS_CHART_VERSION}}"
      release_namespace: "{{REDIS_NAMESPACE}}"
      create_namespace: true
      values:
        global:
          redis:
            password: "{{REDIS_PASSWORD}}"
        master:
          persistence:
            enabled: false 
        replica:
          persistence:
            enabled: false
      wait: true
    register: output
    tags: 
      - redis
      - step2

  - debug:
      var: output
    tags: 
      - redis
      - step2