apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:      
      labels:
        app: nginx    
    spec:      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: web
                operator: In
                values:
                - "true"
      tolerations:
      - key: oss
        operator: Equal
        value: monitoring
        effect: NoSchedule
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
          - name: http
            containerPort: 80