
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-cm
  namespace: nginx
data:
  fluent-bit.conf: |
    [SERVICE]
        flush         2
        log_level     info
        Parsers_File  nginx-parsers.conf
    
    [INPUT]
        name              tail
        tag               nginx
        path              /var/log/nginx/access.log
        parser            nginx

    [OUTPUT]
        name                 opensearch
        match                nginx
        host                 opensearch-ingest-hl.monitoring.svc.cluster.local
        port                 9200
        tls                  Off
        tls.verify           Off
        Suppress_Type_Name   On
        Replace_Dots         On
        Logstash_Format      On
        logstash_prefix      server-nginx-log
        logstash_dateformat  %Y%m%d

    [OUTPUT]
        Name   stdout
        Match  *

  nginx-parsers.conf: |
    [PARSER]
        Name    nginx
        Format  regex
        Regex   /^(?<remote>[^ ]*)\s+(?<host>[^ ]*)\s+(?<user>[^ ]*)\s+\[(?<time>[^\]]*)\]\s+"(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?"\s+(?<code>[^ ]*)\s+(?<size>[^ ]*)(?: "(?<referer>[^\"]*)"\s+"(?<agent>[^\"]*)")\s+"(?<from_ip>[^ ]*)"$/


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
        volumeMounts:
            - name: log-volume
              mountPath: /var/log/nginx

      - name: fluent-bit
        image: bitnami/fluent-bit:2.2.0
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
        - name: fluentbit-config
          mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: parser
          mountPath: /opt/bitnami/fluent-bit/conf/nginx-parsers.conf
          subPath: nginx-parsers.conf

      volumes:
      - name: log-volume
        emptyDir: {}
      - name: fluentbit-config
        configMap:
          name: fluentbit-cm
          items:
          - key: fluent-bit.conf
            path: fluent-bit.conf
      - name: parser
        configMap:
          name: fluentbit-cm
          items:
          - key: nginx-parsers.conf
            path: nginx-parsers.conf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "nginx.3.39.152.82.sslip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
          